package WhosOnFirst;

public enum MiddleWord {
	BLANK, DONE, FIRST, HOLD, LEFT, LIKE, MIDDLE, NEXT, NO, NOTHING, OKAY, PRESS, READY, RIGHT, SURE, U, UHHH, UR,
	UH_HUH, UH_UH, WAIT, WHAT, WHAT_INTERROGATIONMARK, YES, YOU, YOUR, YOURE, YOU_ARE
}
