package WhosOnFirst;

public enum MiddleWord {
	READY, FIRST, NO, BLANK, NOTHING, YES, WHAT, UHHH, LEFT, RIGHT, MIDDLE, OKAY, WAIT, PRESS, YOU, YOU_ARE, YOUR,
	YOURE, UR, U, UH_HUH, UH_UH, WHAT_INTERROGATIONMARK, DONE, NEXT, HOLD, SURE, LIKE
}
