package WhosOnFirst;

public enum TopWord {
	BLANK, C, CEE, DISPLAY, FIRST, HOLD_ON, LEAD, LED, LEED, NO, NONE, NOTHING, OKAY, RED, READ, REED, SAYS, SEE, THEIR,
	THERE, THEYRE, THEY_ARE, UR, YOU, YOU_ARE, YOUR, YOURE, YES
}
