package WhosOnFirst;

public enum TopWord {
	YES, FIRST, DISPLAY, OKAY, SAYS, NOTHING, NONE, BLANK, NO, LED, LEAD, READ, RED, REED, LEED, HOLD_ON, YOU, YOU_ARE,
	YOUR, YOURE, UR, THERE, THEYRE, THEIR, THEY_ARE, SEE, C, CEE
}
